const { WorkoutHistory1790500000000 } = require('../dist/database/migrations/1790500000000-WorkoutHistory');
const { DailyCheckIns1790600000000 } = require('../dist/database/migrations/1790600000000-DailyCheckIns');
const { Nutrition1790700000000 } = require('../dist/database/migrations/1790700000000-Nutrition');
const { NutritionCoachOpinions1790800000000 } = require('../dist/database/migrations/1790800000000-NutritionCoachOpinions');
const { CoachConversations1790900000000 } = require('../dist/database/migrations/1790900000000-CoachConversations');
const { CoachTablePrivileges1791000000000 } = require('../dist/database/migrations/1791000000000-CoachTablePrivileges');
const { AllowJournalDeletion1790400000000 } = require('../dist/database/migrations/1790400000000-AllowJournalDeletion');
require('reflect-metadata');
const { ProgramAcceptance1790300000000 } = require('../dist/database/migrations/1790300000000-ProgramAcceptance');
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { DataSource } = require('typeorm');
const { ConfigService } = require('@nestjs/config');
const { createTestDriver } = require('./pglite-driver.cjs');
const { entities, User, Onboarding, JournalEntry } = require('../dist/database/entities');
const { IdentityAndOnboarding1790000000000 } = require('../dist/database/migrations/1790000000000-IdentityAndOnboarding');
const { TrainingPrograms1790100000000 } = require('../dist/database/migrations/1790100000000-TrainingPrograms');
const { CoachingChat1790200000000 } = require('../dist/database/migrations/1790200000000-CoachingChat');
const { ChatService } = require('../dist/chat/chat.service');
const { ChatConversation, ChatMessage } = require('../dist/chat/chat.entity');
const { ChatAi, answerSchema } = require('../dist/chat/chat-ai');
const { nextQuestion } = require('../dist/chat/questions');
const { projectAnswer } = require('../dist/chat/apply-answer');
const { buildTrainingContext, requiredClarifications } = require('../dist/program/context');
const { validateProgram } = require('../dist/program/validation');
const { programResultSchema } = require('../dist/program/program.schema');
const { normalizeExercise } = require('../dist/program/wger.service');
const { profile, raw, plan } = require('./program-fixtures.cjs');
const answer = overrides => answerSchema.parse({ understood: true, reply: 'Nickel !', firstName: null, weekdays: null, sessionsPerWeek: null, durationMinutes: null, gymType: null, equipment: null, scheduleMode: null, fixedWeekdays: null, fixedMinutes: null, ...overrides });
const context = (p = profile(), details = {}, name = 'Max') => buildTrainingContext(p, 1, name, details);
const mixed = () => ({ ...profile(), sports: ['strength', 'boxing'], days: [0, 1, 3, 5], sessions: 4, duration: '60' });
test('asks only missing essentials; free multisport schedules are decided by the coach', () => {
  assert.equal(nextQuestion(context()), null);
  assert.equal(nextQuestion(context(profile(), {}, null)).key, 'firstName');
  assert.equal(nextQuestion(context(mixed())), null);
  assert.deepEqual(requiredClarifications(context(mixed())), []);
  assert.equal(nextQuestion(context({ ...mixed(), places: ['club'] })).key, 'schedule');
  const details = { schedules: [{ sport: 'boxing', mode: 'fixed', weekdays: [1, 5], minutes: 60 }] };
  assert.equal(nextQuestion(context(mixed(), details)), null);
  const impossible = { ...mixed(), sports: ['strength', 'boxing', 'running'] };
  details.schedules[0].weekdays = [0, 1, 5];
  assert.equal(nextQuestion(context(impossible, details)).key, 'availability');
  assert.ok(requiredClarifications(context(impossible, details)).length);
});
test('structured projection only changes the requested field and retains pain declarations', () => {
  const q = nextQuestion(context(profile(), {}, null));
  const result = projectAnswer(profile(), {}, null, q, answer({ firstName: 'Max', weekdays: [6], sessionsPerWeek: 7 }), 'Je suis Max');
  assert.equal(result.firstName, 'Max'); assert.deepEqual(result.profile.days, [0]);
  assert.equal(projectAnswer(profile(), {}, null, q, answer({ firstName: 'Inventé' }), 'Salut'), null);
  const p = { ...mixed(), places: ['club'] }, schedule = nextQuestion(context(p));
  const scheduled = projectAnswer(p, {}, 'Max', schedule, answer({ scheduleMode: 'fixed', fixedWeekdays: [1, 5], fixedMinutes: 60 }), 'Mardi et samedi une heure');
  assert.deepEqual(scheduled.details.schedules[0].weekdays, [1, 5]);
  const painful = { ...profile(), noPain: false, pains: ['left_wrist'] };
  const restricted = projectAnswer(painful, {}, 'Max', nextQuestion(context(painful)), answer(), 'Les pompes me font mal.');
  assert.deepEqual(restricted.profile.pains, ['left_wrist']); assert.equal(restricted.profile.noPain, false);
});
test('four sessions cover boxing and strength, respecting fixed days and total duration', () => {
  const c = context(mixed(), { schedules: [{ sport: 'boxing', mode: 'fixed', weekdays: [1, 5], minutes: 60 }] });
  const p = plan(), strength = p.sessions[0];
  const boxing = day => ({ name: 'Boxe au club', sport: 'boxing', setting: 'club', weekday: day, warmupMinutes: 5, warmup: 'Échauffement avec le coach.', estimatedMinutes: 60, exercises: [], blocks: [{ title: 'Cours au club', minutes: 55, intensity: 'moderate', instruction: 'Suis les consignes de ton coach.' }] });
  p.sessions = [{ ...strength, weekday: 0 }, boxing(1), { ...strength, weekday: 3 }, boxing(5)];
  const catalog = new Map([1, 2].map(id => [id, normalizeExercise(raw(id))]));
  assert.deepEqual(validateProgram(programResultSchema.parse(p), c, catalog), []);
  for (const change of [v => v.sessions.push(...v.sessions), v => v.sessions[1].weekday = 2, v => v.sessions[1].blocks[0].minutes = 50, v => v.sessions[1].setting = 'self', v => v.sessions[0].exercises[0].exerciseId = 999]) {
    const broken = structuredClone(p); change(broken); assert.ok(validateProgram(broken, c, catalog).length);
  }
});
test('chat uses strict structured output, concise instructions and no provider storage', async () => {
  const ai = new ChatAi(new ConfigService({ OPENAI_API_KEY: 'test-only' }));
  assert.throws(() => new ChatAi(new ConfigService({})).ensureConfigured());
  const original = global.fetch;
  global.fetch = async (url, options) => {
    assert.equal(url, 'https://api.openai.com/v1/responses');
    const body = JSON.parse(options.body);
    assert.equal(body.text.format.strict, true); assert.equal(body.store, false); assert.equal(body.reasoning.effort, 'low'); assert.equal(body.model, 'gpt-5.6-luna');
    assert.equal(body.text.format.schema.additionalProperties, false);
    return new Response(JSON.stringify({ id: 'response-test', status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text: JSON.stringify(answer({ firstName: 'Max' })) }] }] }));
  };
  try { assert.equal((await ai.answer(context(profile(), {}, null), nextQuestion(context(profile(), {}, null)), 'Max', [])).answer.firstName, 'Max'); }
  finally { global.fetch = original; }
});
test('durable onboarding chat persists corrections, deduplicates retries, isolates users and starts generation', async t => {
  const db = new DataSource({ type: 'postgres', driver: createTestDriver(), database: 'postgres', entities, migrations: [IdentityAndOnboarding1790000000000, TrainingPrograms1790100000000, CoachingChat1790200000000, ProgramAcceptance1790300000000, AllowJournalDeletion1790400000000, WorkoutHistory1790500000000, DailyCheckIns1790600000000, Nutrition1790700000000, NutritionCoachOpinions1790800000000, CoachConversations1790900000000, CoachTablePrivileges1791000000000], synchronize: false, installExtensions: false, uuidExtension: 'pgcrypto' });
  await db.initialize(); await db.runMigrations(); t.after(() => db.destroy());
  const users = db.getRepository(User), profiles = db.getRepository(Onboarding), conversations = db.getRepository(ChatConversation), messages = db.getRepository(ChatMessage);
  const user = await users.save({ appleSubject: 'chat-owner' }), other = await users.save({ appleSubject: 'chat-other' });
  await profiles.save({ userId: user.id, profile: { ...mixed(), places: ['club'] }, currentStep: 14, revision: 1, completedAt: new Date() });
  let starts = 0;
  const ai = { ensureConfigured() {}, answer: async () => ({ answer: answer({ firstName: 'Max' }), trace: { mocked: true } }) };
  const service = new ChatService(db, ai, { start: async () => { starts++; } });
  const chat = await service.prepare(user.id); assert.equal(chat.status, 'awaiting_answer');
  assert.equal((await service.prepare(user.id)).messages.length, 1);
  await assert.rejects(service.get(other.id, chat.id), { status: 404 });
  await assert.rejects(service.send(other.id, chat.id, randomUUID(), 'Max'), { status: 404 });
  const requestId = randomUUID();
  await service.send(user.id, chat.id, requestId, 'Max');
  await service.send(user.id, chat.id, requestId, 'Max');
  assert.equal(await messages.countBy({ role: 'user' }), 1);
  await assert.rejects(service.send(user.id, chat.id, requestId, 'Autre'), { status: 409 });
  await service.tick(); assert.equal((await users.findOneByOrFail({ id: user.id })).firstName, 'Max');
  assert.equal((await conversations.findOneByOrFail({ id: chat.id })).question.key, 'schedule'); assert.equal(starts, 0);
  ai.answer = async () => { throw new Error('network failure'); };
  const scheduleId = randomUUID(); await service.send(user.id, chat.id, scheduleId, 'Organise les jours pour moi'); await service.tick();
  assert.equal((await service.get(user.id, chat.id)).status, 'failed');
  ai.answer = async () => ({ answer: answer({ scheduleMode: 'coach', firstName: 'Autre' }), trace: {} });
  await service.send(user.id, chat.id, scheduleId, 'Organise les jours pour moi');
  await conversations.update(chat.id, { status: 'processing', leaseUntil: new Date(0) });
  await service.tick();
  assert.equal((await service.get(user.id, chat.id)).status, 'ready'); assert.equal(starts, 1);
  assert.equal(await messages.countBy({ role: 'user' }), 2);
  const saved = await profiles.findOneByOrFail({ userId: user.id });
  assert.equal(saved.revision, 3); assert.equal(saved.coachingDetails.schedules[0].mode, 'coach');
  assert.equal(await profiles.countBy({ userId: user.id }), 1);
  assert.equal((await users.findOneByOrFail({ id: user.id })).firstName, 'Max');
  const history = await db.getRepository(JournalEntry).findBy({ type: 'profile.coaching_answer_applied' });
  assert.equal(history.length, 2); assert.ok(history.every(h => h.payload.before && h.payload.after));
  await assert.rejects(db.query('UPDATE chat_messages SET text = $1 WHERE conversation_id = $2', ['edited', chat.id]));
  await assert.rejects(db.query('DELETE FROM chat_messages WHERE conversation_id = $1', [chat.id]));
  const fresh = await users.save({ appleSubject: 'chat-stale' });
  await profiles.save({ userId: fresh.id, profile: profile(), revision: 1, completedAt: new Date() });
  const freshChat = await service.prepare(fresh.id);
  ai.ensureConfigured = () => { throw new Error('NO_KEY'); };
  await assert.rejects(service.send(fresh.id, freshChat.id, randomUUID(), 'Alice'), /NO_KEY/);
  assert.equal((await service.get(fresh.id, freshChat.id)).messages.length, 1);
  ai.ensureConfigured = () => {};
  ai.answer = async () => {
    await profiles.update(fresh.id, { revision: 2 });
    return { answer: answer({ firstName: 'Alice' }), trace: {} };
  };
  await service.send(fresh.id, freshChat.id, randomUUID(), 'Alice'); await service.tick();
  assert.equal((await users.findOneByOrFail({ id: fresh.id })).firstName, null);
  assert.equal((await service.get(fresh.id, freshChat.id)).status, 'awaiting_answer');
  ai.answer = async () => {
    await conversations.update(freshChat.id, { turnId: randomUUID() });
    return { answer: answer({ firstName: 'Alice' }), trace: {} };
  };
  await service.send(fresh.id, freshChat.id, randomUUID(), 'Alice'); await service.tick();
  assert.equal((await users.findOneByOrFail({ id: fresh.id })).firstName, null);
  assert.equal((await service.get(fresh.id, freshChat.id)).status, 'processing');
  const schemaChanges = (await db.driver.createSchemaBuilder().log()).upQueries;
  assert.equal(schemaChanges.length, 0, schemaChanges.map(change => change.query).join('\n'));
});
