const { WorkoutHistory1790500000000 } = require('../dist/database/migrations/1790500000000-WorkoutHistory');
const { DailyCheckIns1790600000000 } = require('../dist/database/migrations/1790600000000-DailyCheckIns');
const { Nutrition1790700000000 } = require('../dist/database/migrations/1790700000000-Nutrition');
const { NutritionCoachOpinions1790800000000 } = require('../dist/database/migrations/1790800000000-NutritionCoachOpinions');
const { AllowJournalDeletion1790400000000 } = require('../dist/database/migrations/1790400000000-AllowJournalDeletion');
require('reflect-metadata');
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { DataSource } = require('typeorm');
const { ConfigService } = require('@nestjs/config');
const { createTestDriver } = require('./pglite-driver.cjs');
const { entities, User, Onboarding, JournalEntry } = require('../dist/database/entities');
const { IdentityAndOnboarding1790000000000 } = require('../dist/database/migrations/1790000000000-IdentityAndOnboarding');
const { TrainingPrograms1790100000000 } = require('../dist/database/migrations/1790100000000-TrainingPrograms');
const { CoachingChat1790200000000 } = require('../dist/database/migrations/1790200000000-CoachingChat');
const { ProgramAcceptance1790300000000 } = require('../dist/database/migrations/1790300000000-ProgramAcceptance');
const { TrainingProgram } = require('../dist/program/program.entity');
const { ProgramService } = require('../dist/program/program.service');
const { ProgramGenerator } = require('../dist/program/generator');
const { ChatAi } = require('../dist/chat/chat-ai');
const { ChatService } = require('../dist/chat/chat.service');
const { ProgramReviewService } = require('../dist/chat/program-review.service');
const { ChatConversation, ChatMessage } = require('../dist/chat/chat.entity');
const { buildTrainingContext } = require('../dist/program/context');
const { normalizeExercise } = require('../dist/program/wger.service');
const { profile, raw, plan } = require('./program-fixtures.cjs');
const output = () => ({ result: plan(), exercises: [1, 2].map(id => normalizeExercise(raw(id))), trace: {} });

test('review responses distinguish a question from an adjustment and reuse the validated generation pipeline', async () => {
  const original = global.fetch, requests = [];
  const config = new ConfigService({ OPENAI_API_KEY: 'test-only' });
  const context = buildTrainingContext(profile(), 1, 'Max');
  global.fetch = async (url, options) => {
    const body = JSON.parse(options.body); requests.push(body);
    const result = body.text.format.name === 'program_review' ? { action: 'answer', reply: 'Les jours de repos te laissent récupérer.', instruction: null } : plan();
    return new Response(JSON.stringify({ id: 'test-response', status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text: JSON.stringify(result) }] }] }));
  };
  try {
    const answer = await new ChatAi(config).review(context, output(), 'Pourquoi ces jours ?', []);
    assert.equal(answer.answer.action, 'answer');
    assert.equal(requests[0].model, 'gpt-5.6-terra'); assert.equal(requests[0].reasoning.effort, 'medium');
    assert.equal(answer.trace.model, requests[0].model); assert.equal(answer.trace.reasoningEffort, 'medium'); assert.equal(requests[0].store, false);
    assert.equal(requests[0].text.format.strict, true); assert.ok(JSON.parse(requests[0].input[0].content).program.result.sessions.length);
    const revised = await new ProgramGenerator(config, {}).generate(context, async () => {}, AbortSignal.timeout(2000), { request: 'Garde les exercices, change le nom.', previous: output() });
    assert.equal(revised.result.outcome, 'ready');
    assert.equal(requests[1].model, 'gpt-5.6-sol'); assert.equal(requests[1].reasoning.effort, 'high');
    assert.equal(revised.trace.model, requests[1].model); assert.equal(revised.trace.reasoningEffort, 'high');
    assert.ok(JSON.parse(requests[1].input[0].content).previousProgram);
  } finally { global.fetch = original; }
});

test('proposal review is durable, questions do not modify plans and acceptance is explicit, fenced and idempotent', async t => {
  const db = new DataSource({ type: 'postgres', driver: createTestDriver(), database: 'postgres', entities,
    migrations: [IdentityAndOnboarding1790000000000, TrainingPrograms1790100000000, CoachingChat1790200000000, ProgramAcceptance1790300000000, AllowJournalDeletion1790400000000, WorkoutHistory1790500000000, DailyCheckIns1790600000000, Nutrition1790700000000, NutritionCoachOpinions1790800000000], synchronize: false, installExtensions: false, uuidExtension: 'pgcrypto' });
  await db.initialize(); await db.runMigrations(); t.after(() => db.destroy());
  const profiles = db.getRepository(Onboarding), programs = db.getRepository(TrainingProgram), chats = db.getRepository(ChatConversation);
  const user = await db.getRepository(User).save({ appleSubject: 'review-owner', firstName: 'Max' });
  const other = await db.getRepository(User).save({ appleSubject: 'review-other', firstName: 'Jo' });
  await profiles.save({ userId: user.id, profile: profile(), currentStep: 14, revision: 1, completedAt: new Date() });
  const generator = { ensureConfigured() {}, settings: () => ({}), generate: async () => output() };
  const service = new ProgramService(db, generator);
  await service.start(user.id); await service.tick();
  const proposal = await service.get(user.id); assert.equal(proposal.acceptedAt, null);
  const ai = { ensureConfigured() {}, review: async () => ({ answer: { action: 'answer', reply: 'Pour récupérer entre tes séances.', instruction: null }, trace: {} }) };
  const review = new ProgramReviewService(db, ai, generator), common = new ChatService(db, ai, service);
  const chat = await review.open(user.id); assert.equal((await review.open(user.id)).messages.length, 1);
  await assert.rejects(common.get(other.id, chat.id), { status: 404 });
  const requestId = randomUUID();
  await review.send(user.id, chat.id, requestId, 'Pourquoi ces jours ?', proposal.proposalId);
  await review.send(user.id, chat.id, requestId, 'Pourquoi ces jours ?', proposal.proposalId);
  assert.equal(await db.getRepository(ChatMessage).countBy({ role: 'user' }), 1);
  await assert.rejects(common.send(user.id, chat.id, randomUUID(), 'Wrong endpoint'), { status: 409 });
  await assert.rejects(service.accept(user.id, proposal.proposalId), { status: 409 });
  await common.tick(); assert.equal((await common.get(user.id, chat.id)).status, 'queued');
  await review.tick(); assert.equal((await common.get(user.id, chat.id)).status, 'awaiting_answer');
  assert.equal((await service.get(user.id)).proposalId, proposal.proposalId);
  assert.equal((await service.get(user.id)).acceptedAt, null);
  ai.review = async () => ({ answer: { action: 'revise', reply: 'Je regarde.', instruction: 'Change le titre.' }, trace: {} });
  generator.generate = async () => ({ ...output(), result: { ...plan(), title: 'Nouvelle proposition' } });
  const adjustId = randomUUID(); await review.send(user.id, chat.id, adjustId, 'Change le titre.', proposal.proposalId);
  await chats.update(chat.id, { status: 'processing', leaseUntil: new Date(0) });
  await review.tick();
  const revised = await service.get(user.id);
  assert.notEqual(revised.proposalId, proposal.proposalId); assert.equal(revised.result.title, 'Nouvelle proposition'); assert.equal(revised.acceptedAt, null);
  assert.equal(await programs.countBy({ userId: user.id }), 1);
  const history = await db.getRepository(JournalEntry).findOneByOrFail({ type: 'program.proposal_adjusted' });
  assert.equal(history.payload.before.result.title, plan().title); assert.equal(history.payload.after.result.title, 'Nouvelle proposition');
  await assert.rejects(service.accept(user.id, proposal.proposalId), { status: 409 });
  assert.equal((await review.send(user.id, chat.id, adjustId, 'Change le titre.', proposal.proposalId)).status, 'awaiting_answer');
  generator.generate = async () => { throw new Error('NETWORK'); };
  const failedId = randomUUID(); await review.send(user.id, chat.id, failedId, 'Autre titre.', revised.proposalId); await review.tick();
  assert.equal((await common.get(user.id, chat.id)).status, 'failed'); assert.equal((await service.get(user.id)).proposalId, revised.proposalId);
  ai.review = async () => ({ answer: { action: 'answer', reply: 'On garde cette proposition.', instruction: null }, trace: {} });
  await review.send(user.id, chat.id, failedId, 'Autre titre.', revised.proposalId); await review.tick();
  assert.equal(await db.getRepository(ChatMessage).countBy({ role: 'user' }), 3);
  const accepted = await service.accept(user.id, revised.proposalId);
  assert.ok(accepted.acceptedAt); assert.equal((await service.accept(user.id, revised.proposalId)).acceptedAt.getTime(), accepted.acceptedAt.getTime());
  assert.equal(await db.getRepository(JournalEntry).countBy({ type: 'program.accepted' }), 1);
  await assert.rejects(review.send(user.id, chat.id, randomUUID(), 'Change.', revised.proposalId), { status: 409 });
  await profiles.update(user.id, { revision: 2 });
  await assert.rejects(service.accept(user.id, revised.proposalId), { status: 409 });
  generator.generate = async () => output(); await service.start(user.id); await service.tick();
  const next = await service.get(user.id); assert.equal(next.acceptedAt, null);
  await review.open(user.id); await review.send(user.id, chat.id, randomUUID(), 'Pourquoi ?', next.proposalId);
  ai.review = async () => { await profiles.update(user.id, { revision: 3 }); return { answer: { action: 'answer', reply: 'Réponse obsolète', instruction: null }, trace: {} }; };
  await review.tick(); assert.equal((await common.get(user.id, chat.id)).status, 'failed');
  assert.ok(!(await common.get(user.id, chat.id)).messages.some(m => m.text === 'Réponse obsolète'));
  assert.equal((await db.driver.createSchemaBuilder().log()).upQueries.length, 0);
});
