/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/coach`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/program`; params?: Router.UnknownInputParams; } | { pathname: `/progression`; params?: Router.UnknownInputParams; } | { pathname: `/squad`; params?: Router.UnknownInputParams; } | { pathname: `/today`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/nutrition/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/features/nutrition/components/BarcodeScanner`; params?: Router.UnknownInputParams; } | { pathname: `/../src/features/coach/coachApi`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/coach`; params?: Router.UnknownOutputParams; } | { pathname: `/components`; params?: Router.UnknownOutputParams; } | { pathname: `/game`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/nutrition`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/pending`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/program`; params?: Router.UnknownOutputParams; } | { pathname: `/progression`; params?: Router.UnknownOutputParams; } | { pathname: `/squad`; params?: Router.UnknownOutputParams; } | { pathname: `/today`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/services/nutrition/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/features/nutrition/components/BarcodeScanner`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/features/coach/coachApi`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/coach${`?${string}` | `#${string}` | ''}` | `/components${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/nutrition${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/pending${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/program${`?${string}` | `#${string}` | ''}` | `/progression${`?${string}` | `#${string}` | ''}` | `/squad${`?${string}` | `#${string}` | ''}` | `/today${`?${string}` | `#${string}` | ''}` | `/../src/services/nutrition/index${`?${string}` | `#${string}` | ''}` | `/../src/features/nutrition/components/BarcodeScanner${`?${string}` | `#${string}` | ''}` | `/../src/features/coach/coachApi${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/coach`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/nutrition`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/program`; params?: Router.UnknownInputParams; } | { pathname: `/progression`; params?: Router.UnknownInputParams; } | { pathname: `/squad`; params?: Router.UnknownInputParams; } | { pathname: `/today`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/nutrition/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/features/nutrition/components/BarcodeScanner`; params?: Router.UnknownInputParams; } | { pathname: `/../src/features/coach/coachApi`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
