const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
function load(relative,deps){const file=path.resolve(__dirname,relative);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};vm.runInNewContext(code,{exports,require:name=>{if(name in deps)return deps[name];throw Error(name);},console,Map,Set,Promise,JSON,Error});return exports;}
function fixture(files=new Map()){const file={documentDirectory:'/private/',readAsStringAsync:async p=>{if(!files.has(p))throw Error('missing');return files.get(p);},writeAsStringAsync:async(p,value)=>files.set(p,value)};return{files,storage:load('../src/storage/workouts.ts',{'expo-file-system/legacy':file,'react-native':{Platform:{OS:'ios'}}})};}
test('local writes serialize, recover after restart and keep accounts separate',async()=>{const {files,storage}=fixture();await Promise.all(Array.from({length:10},(_,i)=>storage.updateWorkouts('one',c=>{c.sessions[i]={id:String(i)};})));assert.equal(Object.keys((await storage.readWorkouts('one')).sessions).length,10);assert.equal(Object.keys((await storage.readWorkouts('two')).sessions).length,0);const restored=fixture(files).storage;assert.equal(Object.keys((await restored.readWorkouts('one')).sessions).length,10);
 const latest=[...files.entries()].sort((a,b)=>JSON.parse(b[1]).sequence-JSON.parse(a[1]).sequence)[0][0];files.set(latest,'partial-write');assert.equal(Object.keys((await fixture(files).storage.readWorkouts('one')).sessions).length,9);});
test('outbox retries the identical request after a lost response and retains conflicts',async()=>{const {storage}=fixture();let token='owner-token',calls=[],fail=true,conflict=false;class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}
 const api=load('../src/services/workouts/index.ts',{'expo-crypto':{randomUUID:(()=>{let i=0;return()=>`request-${++i}`;})()},'@/storage/workouts':storage,'@/storage/session':{getSessionToken:()=>token},'@/services/http':{ApiError,apiRequest:async(url,options)=>{calls.push(options.body);if(conflict)throw new ApiError(409,'Conflict');if(fail){fail=false;throw Error('response lost');}return {acknowledgedRevision:options.body.revision+1,session:{}};}}});
 await api.queueWorkout('one','session',{status:'in_progress'});await api.syncWorkouts('one');assert.equal((await storage.readWorkouts('one')).sessions.session.pending.length,1);await api.syncWorkouts('one');assert.equal(calls[0].requestId,calls[1].requestId);assert.equal((await storage.readWorkouts('one')).sessions.session.pending.length,0);
 conflict=true;await api.queueWorkout('one','session',{status:'in_progress'});await api.syncWorkouts('one');assert.equal((await storage.readWorkouts('one')).sessions.session.pending.length,1);assert.equal((await storage.readWorkouts('one')).sessions.session.error,'Conflict');
 token=null;await api.queueWorkout('one','session',{status:'completed'});await api.syncWorkouts('one');assert.equal((await storage.readWorkouts('one')).sessions.session.pending.length,2);
});
