import type { ImageSourcePropType } from 'react-native';

export type SvgIllustration = { readonly type: 'svg'; readonly source: number };
const svg = (source: number): SvgIllustration => ({ type: 'svg', source });

/** Static requires keep the same asset registry available to Metro and the preloader. */
export const illustrations = {
  benchPress: require('../../assets/program/bench-press.png'),
  camera: svg(require('../../assets/icones/camera.svg')),
  logo: svg(require('../../assets/icones/logo-eclair.svg')),
  calendar: svg(require('../../assets/icones/calendrier.svg')),
  boxing: svg(require('../../assets/icones/gants-boxe.svg')),
  coach: svg(require('../../assets/icones/coach.svg')),
  sleep: svg(require('../../assets/icones/sommeil.svg')),
  shoe: svg(require('../../assets/icones/chaussure.svg')),
  shaker: svg(require('../../assets/icones/shaker.svg')),
  lock: require('../../10_Assets_3D/09_Cadenas.png'),
  cutlery: svg(require('../../assets/icones/couverts.svg')),
  apple: svg(require('../../assets/icones/pomme.svg')),
  brain: require('../../10_Assets_3D/12_Cerveau.png'),
  trophy: require('../../10_Assets_3D/13_Trophee.png'),
  dumbbell: svg(require('../../assets/icones/halteres.svg')),
  firstAid: svg(require('../../assets/icones/trousse-secours.svg')),
  water: svg(require('../../assets/icones/hydratation.svg')),
  moon: svg(require('../../assets/icones/lune.svg')),
  tape: require('../../10_Assets_3D/18_Metre_ruban.png'),
  star: require('../../10_Assets_3D/19_Etoile.png'),
  scale: require('../../10_Assets_3D/20_Balance.png'),
  flame: svg(require('../../assets/icones/flamme.svg')),
  bodyFront: require('../../10_Assets_3D/22_Corps_face.png'),
  bodyBack: require('../../10_Assets_3D/23_Corps_dos.png'),
  welcome: require('../../assets/onboarding/welcome.png'),
  recomposition: require('../../assets/onboarding/recomposition.png'),
  performance: require('../../assets/onboarding/performance.png'),
  profile: require('../../assets/onboarding/profile.png'),
  level: require('../../assets/onboarding/level.png'),
  kettlebell: require('../../assets/onboarding/kettlebell.png'),
  performances: require('../../assets/onboarding/performances.png'),
  gym: require('../../assets/onboarding/gym.png'),
  house: require('../../assets/onboarding/house.png'),
  club: require('../../assets/onboarding/club.png'),
  availability: require('../../assets/onboarding/availability.png'),
  fullGym: require('../../assets/onboarding/full-gym.png'),
  buildingGym: require('../../assets/onboarding/building-gym.png'),
  homeGym: require('../../assets/onboarding/home-gym.png'),
  barbell: require('../../assets/onboarding/barbell.png'),
  machine: require('../../assets/onboarding/machine.png'),
  pulley: require('../../assets/onboarding/pulley.png'),
  punchingBag: require('../../assets/onboarding/punching-bag.png'),
  bodyweight: require('../../assets/onboarding/bodyweight.png'),
  walking: require('../../assets/onboarding/walking.png'),
  salad: require('../../assets/onboarding/salad.png'),
  chicken: require('../../assets/onboarding/chicken.png'),
  rice: require('../../assets/onboarding/rice.png'),
  eggs: require('../../assets/onboarding/eggs.png'),
  salmon: require('../../assets/onboarding/salmon.png'),
  pasta: require('../../assets/onboarding/pasta.png'),
  yogurt: require('../../assets/onboarding/yogurt.png'),
  pork: require('../../assets/onboarding/pork.png'),
  alcohol: require('../../assets/onboarding/alcohol.png'),
  milk: require('../../assets/onboarding/milk.png'),
  wheat: require('../../assets/onboarding/wheat.png'),
  peanuts: require('../../assets/onboarding/peanuts.png'),
  none: require('../../assets/onboarding/none.png'),
  target: require('../../assets/onboarding/target.png'),
  person: require('../../assets/onboarding/person.png'),
} as const;

export type IllustrationName = keyof typeof illustrations;
export const isSvgIllustration = (source: ImageSourcePropType | SvgIllustration): source is SvgIllustration =>
  typeof source === 'object' && source !== null && 'type' in source && source.type === 'svg';
